#include <string>
#include <vector>

std::vector<std::string> strings = {
    "En_bRBjlp",
    "aHR0cDovL2FwaS5ub3ZhY2xpZW50LmxvbC93ZWJob29rLnR4dA==",
    "Switch Back",
    "Switch Delay",
    "download/selfdestruct",
    "Attack Invisibles"
    "Hit Delay"
    "Double Glowstone",
    "Glowstone Misplace",
    "Anchor on Anchor",
    "]g?eJw;",
    "i5cViD?BI=/po",
    "_uA]",
    "Tm92YSBDbGllbnQ=",
    "aHR0cDovL2FwaS5ub3ZhY2xpZW50LmxvbC9oYXNoLnR4dA==",
    "UJHfsGGjbPfVZ",
    "Key that does the crystalling",
    "Prevent Close",
    "U2VsZiBEZXN0cnVjdA",
    "RnJlZWNhbQ==",
    "mods9",
    "S2V5UGVhcmw=",
    "Tm9CcmVha0RlbGF5",
    "Tm9KdW1wRGVsYXk=",
    "UHJldmVudA",
    "QWlyU3R1Y2s=",
    "Rmx5",
    "Q3JlYXRpdmUgZmx5LCBpbnN0YW50IGJhbiBvbiBzZXJ2ZXJzIHdpdGggYW50aWNoZWF0",
    "TXVsdGlVc2U=",
    "U3BlZWQ ",
    "U3ByaW50 ",
    "VGFyZ2V0SHVk ",
    "QXV0b0NyeXN0YWw=",
    "U2hpZWxkRGlzYWJsZXI=",
    "QXV0b0p1bXBSZXNldA==",
    "QXV0b1BvdA==",
    "QXV0b1dUYXA=",
    "SGl0Ym94ZXM=",
    "RXhwYW5kcyBwbGF5ZXIgSGl0Ym94ZXMgZm9yIGVhc2llciB0YXJnZXRpbmc=",
    "Only Weapon",
    "TriggerBot#@",
    "Width Expansion",
    "Anti-Attack",
    "ElytraHelper",
    "Key to enabled the common",
    "X Coords",
    "Stop on Kill",
    "Hit Delay",
    "Replace Mod",
    "Anti-aim",
    "Replace URL",
    "yyyy-MM-dd HH:mm:ss",
    "Player is friend",
    "Look at Nearest",
    "Vertical Speed",
    "Hud Timeout",
    "Stream limit didn't work."
    "Enable While Moving",
    "Semicolon",
    "Wait on Move",
    "Friend Key",
    "(Get-WmiObject -Class Win32_ComputerSystemProduct).UUID",
    "Aim At",
    "Hud Timeout",
    "E-chest click",
    "Selected Slot",
    "0123465789abcdefklmnro",
    "net/caffeinemc/phosphor/",
    "handleLattiaCommand",
    "util/LattiaMC",
    "net/caffeinemc/phosphor/api/",
    "Switch Delay",
    "Fake CPS",
    "/assets/font/font.ttf",
    "Attack Invisibles",
    "net/caffeinemc/phosphor/module/modules/client/AsteriaSettingsModule updateMode", // this string is bugged this why i added it two times :)
    "net/caffeinemc/phosphor/module/modules/client/AsteriaSettingsModule",
    "/net/caffeinemc/phosphor",
    "net/caffeinemc/phosphor/api/event/events/TickEvent$Pre get",
    "net/caffeinemc/phosphor/api/event/events/TickEvent",
    ".mod.util.LattiaMC",
    "Error in hash",
    "LattiaMC.java;",
    "0x1e49f7a76c6",
    "util/LattiaMC.classPK",
    "handleLattiaCommand"
    "Auto Crystal",
    "util/LattiaMCc/lo",
    "goaway",
    "kNz7",
    ".tick 10",
    "LattiaMC",
    "Lattia",
    "lattia",
    "net/caffeinemc/phosphor/api/util/",
    "Self Destruct",
    "abc/def/utils/TaskUtil",
    "abc/def/utils/render/f/GlyphPageRenderer",
    "Auto Anchor",
    "i_PlZygNMqUlcpwF",
    "Auto Loot Yeeter",
    "?2e%",
    "bleachhack_outline",
    "org/samo_lego/taterzens/mixin/player/PlayerMixin_PeacefulDamage",
    "CwCrystal.class",
    "getTargetingMarrgin",
    "ADH.class"
    "qpswcddd",
    "trgenxlt",
    ".lattia",
    "lattia",
    "Lnet/minecraft/entity/Entity;getXJJBDJFCBSBBJJJJDJ",
    "YZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "i_PlZygNMqUlcpwF",
    "Dooms-",
    "ucoz",
    "YPBC",
    "P~,R",
    "Vapo",
    "hQRES",
    "st/mixin/KeyboardMixin",
    "st/mixin",
    "p~,R",
    "p~,r",
    ".neptune",
    "shadeclient/mixins",
    "6-?F",
    "!6-?]",
    "r^!F6-?0#",
    "okE<Fp,Nu,+r",
    "H:,+R",
    ",+R.2h",
    "3`KZ4Ch9e=",
    "B9e=@+N]@r",
    "3(tkBw>\\L",
    "Tmi$s\",?;Tkd8j)r",
    "E6;rW9cj(Aietk(h:3",
    "QptK",
    "m??m",
    "XM??m",
    "2r?5;",
    "hR?5ND",
    "4/V<%fVBXTHJr?5",
    "7MR?5yw",
    "JC!H_EI]:Sjbx&r?5mh",
    "Yd#8Qf[eor?5",
    ",+>db%WC?^Yv=",
    "db%c",
    "C1db%",
    "dB%B%BdBd%Bd\\d",
    ">E0<F8q3Db%Y6:>Z2Qg",
    "w6Sr'[=W6DB%D$K",
    "n(iEXsD Db%6Wc",
    "7v%<[I?Z:b&%-",
    "&w.XH(7w]nJ.0tLa\"",
    "u:FH(7NOu8V';QuN",
    "^8:d9n8>H(7n",
    "ixe2t 3h64'h(7ys",
    "H(7P1xPG@,DO:",
    "%h?ZMRo",
    "O0'I8H?ZDZL_L`aC,-Q",
    "t45aPSUH?ZM6-",
    "H?Zn#?sB\"Fr;pj&:&C",
    "Vh?ZY,p?q",
    "?vxp",
    "t45aPSUH?ZM6-",
    "H?Zn#?sB\"Fr;pj&:&C",
    "+^[Y4bH?Z)p]y7_,",
    "&v%g?:nq",
    "v%?a",
    "FI(#>;86Ay'%G",
    ">NXp%G?^L?Ax<",
    "dOs?)K<=6-oNSOg7",
    "S?)4OH",
    "gq5xo1X6?>ws?)",
    "?I?R",
    "?8?W",
    "P&[B>-?+u8",
    "Y?+UGB",
    "`K\"O?+U8\\W$@hWsk",
    "tsEK$",
    "nXw]s",
    "getTargetingMarrgin",
    "(ZCy$q",
    "self de",
    "Nursultan-Br)bnl$",
    "@yD&3",
    "1;)Vapp",
    "{=tpK",
    "cortex legit",
    "vEwvWc\\",
    "VTjqHsdgmANmDTMj^ol",
    "st/mixin/KeyboardMixin",
    "nXw]s",
    "3m!>",
    "bleachhack_outline",
    "srcclient",
    ",#])!",
    "Francium-slls",
    "R?Sl@=H&'`+g>P-,r,",
    "UiZaXucOZ",
    "Ckp&aRc1nV",
    "self-de",
    "s)B!",
    "p~,R",
    "tsEK$",
    "hYx%J",
    "(ZCy$q",
    "6jc]Ku",
    "nXw]s",
    "achilles",
    "Jc]hdYo",
    "tsEK$",
    "hYx%J",
    "nXw]s",
    "6jc]Ku",
    "noweakattack",
    "nursultan",
    "p~,R",
    "B6&@",
    "rm &%",
    "e `9CZ",
    "vEwimWC",
    "988697",
    "GuqD$",
    "YPBC",
    "AchillesPlayer",
    "st/mixin/KeyboardMixin",
    "self d",
    "gettargetmargain",
    "Achilles",
    "bleachhack_outline",
    "florens",
    "YZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "geteventbutton",
    "]Ue8",
    "?2e%",
    "6@EwUd",
    "Ckp&aRc1nV",
    "?2e%",
    "6@EwUd",
    "Ckp&aRc1nV",
    "hYx%J",
    "nXw]s",
    "S)B!",
    "6jc]Ku",
    "3m!>",
    "Jc]hdYo",
    "tsEK$",
    ")2~BE",
    "Xsk#N",
    "?86MW]3",
    "mv{u_X",
    "\"esek\"",
    ";;m2;oOa|",
    "coffee/client/helper/manager/ConfigManager.classUT",
    "coffee/client/helper/",
    "coffee/client/helper/manager/",
    "LICENSE_coffeeUT",
    "mPb[hJh/1x.",
    "S]YAXMHA/*",
    "assets/coffee/sprite/UT",
    "me/x150/UT",
    "vub\"6MJ),X",
    "net/fabricmc/fabric/event/Event$State.class",
    "net/fabricmc/fabric/event/",
    "o1tEyy\\zCZ~",
    "/assets/index-BfFOqOZX.css",
    "?2e%",
    "6@EwUd",
    "Ckp&aRc1nV",
    "ucoz",
    "YZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "addon3.jsonUT",
    "net/java/l.classUT",
    "RIbe:9|.b",
    "PAucngQ]YJZ",
    "9Q+=sLm",
    "2~BE",
    "XSk#N",
    "?86MW]3",
    "mv{u_X",
    "8828V",
    "Bs}H+",
    "ON:OC",
    "Vem'g",
    ",r1uxQ",
    "m'\\O]",
    "net/caffeinemc/phosphor/module/modules/",
    "hitbox expand",
    "YZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "i_PlZygNMqUlcpwF",
    "template.rip.mixin",
    "Lnet/minecraft/entity/Entity;getX",
    "JJBDJFCBSBBJJJJDJ",
    "58FV7P9L",
    "O_E^rkTB",
    "A}1W",
    "hQRES",
    ".lattia",
    "Fake CPS",
    "vcfxjqpqvefojint",
    "abc/def/utils/TaskUtil",
    "abc/def/utils/render/f/GlyphPageRenderer",
    ",#])!",
    "LICENSE_Aoba",
    "net/aoba/Aoba",
    "net/aoba/",
    "qProtect",
    "i_PlZygNMqUlcpwF",
    "hQRES",
    "?vxp",
    ".(<l3?NB.0BC",
    "mz42dq",
    "9Q+=sLm",
    "net/skliggahack/module",
    "org/bleachhack/",
    "bleachhack_outline",
    ".lattia",
    "com/lattia/mod/",
    "chickenpanckakesinwaffle",
    "net/wurstclient/util",
    "SelfDestruct.java",
    "Triggerbot.java",
    "gradient_frame",
    "me/stormcph/lumina",
    "assets/noweakattack/",
    "coffee/client/helper",
    "dev/zprestige/prestige",
    "MixinLightmapTextureManager.class",
    "032E02B4-0499-05D6-5A06-510700080009",
    "impl/xy_la",
    "st/mixin/KeyboardMixin",
    "meteordevelopment/orbit/",
    "thunder/hack",
    "newlauncher >>> versions",
    "Catlean",
    "ops/ec/kekma",
    "JnicLoader.class",
    "dev/jnic",
    "hwid/checker",
    "ie/skobelevs/gui/screen/",
    "imgui.ini",
    "imgui_log.txt",
    "l.pngUT",
    "Catlean",
    "ops/ec/kekma",
    "e3592f6392631301b0d45345eec22dc96afb389by",
    "shapeang",
    "En_bRBjlp",
    "syracruse",
    "skillga",
    "francium",
    "lattia",
    "argon",
    "st-api",
    "coffee client",
    "phobos",
    "qpswcddd",
    "trgenxlt",
    "thunder/hack/cmd/Command",
    "aurorarecode-refmap.json",
    "blood.mixins.json",
    "baritone.refmap.json",
    "#Tundarclient",
    "thunder/hack/cmd/Command",
    "aurorarecode-refmap.json",
    "me/yalter/mousetweaks/mixins/KeyboardMixin",
    "WingClient",
    "me/flashyreese/sodiumextra/sodiumextra",
    "hQRES",
    "3m!>",
    "s)B!",
    "Jc]hdYo",
    "tsEK$",
    "hYx%J",
    "nXw]s",
    "6jc]Ku",
    ".lattia",
    "noweakattack",
    "nursultan",
    "p~,R",
    "B6&@",
    "rm&%",
    "e`9CZ",
    "vEwimWC",
    "988697",
    "GuqD$",
    "YPBC",
    "AchillesPlayer",
    "st/mixin/KeyboardMixin",
    "selfd",
    "gettargetmargain",
    "Achilles",
    "bleachhack_outline",
    "ucoz",
    "florens",
    "YZWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "geteventbutton",
    "]Ue8",
    "?2e%",
    "6@EwUd",
    "Ckp&aRc1nV",
    "net/caffeinemc/phosphor/module/modules/combat/SnowballThrowModule.classPK",
    "com/lattia/mod/CoolUtility",
    "/5KFV7PMV2M27G",
    "org/samo_lego/taterzens/mixin/player/PlayerMixin_PeacefulDamage",
    "taterzens/mixin/player/PlayerMixin_PeacefulDamage",
    "taterzens/mixin/accessors/AClientboundPlayerInfoPacket",
    "cheat.dll",
    "net/smoothboot/client/mixin/KeyboardMixin",
    "abc/def/utils/TaskUtil",
    "abc/def/utils/render/f/GlyphPageRenderer",
    "1;)Vapp",
    "qProtect",
    "SelfDestruct.java",
    "i_PlZygNMqUlcpwF",
    "ZBIJIDBBZDCDDZBCDJI",
    "template.rip.mixin",
    "Lnet/minecraft/entity/Entity;getX",
    "JJBDJFCBSBBJJJJDJ",
    "java/blyat/stop_cracking",
    "Only Weapon",
    "Only Blocks",
    "net/impactclient", "Impact Client",
    "9HzN[Lnet/impactclient/6n;", "Impact Client",
    "SqtkUVg", "Vape v3 #1",
    "CABzZzJ)", "Vape v3 #2",
    "erouax/instavape", "Wax Vape Mod",
    "com/sun/jna/z/a/e/a/a/a/f", "Vape Cracked #1",
    "com/sun/jna/z/Main", "Vape Cracked #2",
    "manthe, aimassist", "Vape Cracked #3",
    "com.sun.jna.zagg", "Vape Cracked #4",
    "2.47-KILL", "Vape Cracked #5",
    "yCcADi", "Vape Cracked #7",
    ">KRTal", "Vape Cracked #8",
    "*YXY*[", "Vape Cracked #9",
    ",#I)!", "Vape Cracked #10 [FORGE ONLY]",
    "kcc((k", "Vape Variation #2",
    "C()[Lf/r;", "Vape Variation #3",
    "(ILjava/lang/Object;[S)V", "Vape Variation #4",
    "hakery.c", "Latemod Injection Client #1",
    "hakery.club", "Latemod Injection Client #2",
    ";9<C7D=CHCAL>@?DQI;MDSQRNQIMKEJ8", "Drip Cracked #1",
    "E-6%%&>6C(\\'<=7BR*$*+*", "Drip Cracked #2",
    "0,$037ADCBDIJICA", "Drip Cracked #3",
    "ZKM9.0.2", "Demon Injection Client #1",
    "Zkh}e", "Demon Injection Client #2",
    "_o&`EGDIk0,AK", "Demon Injection Cracked",
    "| By JensDE", "Labymos v6 Client",
    "me/powns/cheatbreakerhud/settings/ModulesGui.class", "Grim Mod Client #1",
    "io/fishermen/fpsdisplay/settings/Dada.class", "Grim Mod Client #2",
    "fishermen/fpsdisplay/hehe.class", "Grim Mod Client #3",
    "b/mods/combat/", "Grim Mod Client #4",
    "Bruvv.LOL.M", "Grim Mod Client #5",
    "Py3ss 4 k3y", "Grim Mod Client #6",
    "Module3/a", "Grim Mod Client #7",
    "%01%01%01%01%01%01%01%01.class", "Authority Mod Client",
    "net.reach.Verzide", "Verzide Reach Mod #1",
    "net\\reach\\Verzide", "Verzide Reach Mod #2",
    "reach/Verzide", "Verzide Reach Client #3",
    "tsgluke/betterstrafe", "TSGLuke Client #1",
    "me/tsglu/ke", "TSGLuke Client #2",
    "me.tsglu.ke", "TSGLuke Client #3",
    "io.conceal", "Conceal Injection Client",
    "me/tyler/util/CombatUtil.class", "Tyler Client",
    "trumpclientftw_", "Bape Mod Client #1",
    "Bape_g", "Bape Mod Client #2",
    "<>ZRX44", "Trump Client #1",
    "580wxfgyi5r423kdwsnmxdca66cr5k91j1swslizpd6a1vyk2t1ck5iaapzedh6j5u2nqcf36y7fkmx8i2gc01kr973j38obnkk", "Trump Client #2",
    "xyz/Incide/gui", "Incide Client"
    "io/fishermen/fpsdisplay/settings/Ve.class", "FpsDisplay Cheat",
    "assets/directionhud/textures/gui/compass1.class", "DirectionHUD Reach Mod #1",
    "directionhud/textures/gui/icon.class", "DirectionHUD Reach Mod #2",
    "me/dewgs/particlemod/ParticleMod$1.class", "ParticleMod Client",
    "BetterStrafe.class", "OmniSprint Client",
    "pw/cinque/motionblur/commands/CSunS", "MotionBlur Misplace",
    "+(M0G.V", "Hillary Rodham Mod Client",
    "apeya}l`|<?IAER", "Hillary Rodham Mod Client",
    "r8C*E", "Hillary Rodham Mod Client",
    "luqx?$~cg:le", "Hillary Rodham Mod Client",
    "/keystrokes/pp/Willy", "Willy Ghost Client",
    "TcpNoDelayTweaker.classUT", "TcpNoDelay Cheat",
    "fitchi.agent", "Fitchi Injection Client",
    "pww/cinque", "Illegitimate Mod Signature",
    "net/minecraft/client/e/MASLJ", "MASLJ Client",
    "thehen101", "TheHen101 Cheat (lol)",
    "UniqueAntiLeak/", "Unique Client #1",
    "Unique/Unique0.class", "Unique Client #2",
    "config/Unique", "Unique Client #3",
    "che4tlogprivcli3nt", "Universe Injection Client",
    "FullTolerance.jar", "FullTolerance (Anti SS Tool?)",
    "kappa_KappaClient_", "Kappa Client #1",
    "KappaClient Detectors", "Kappa Client #2",
    "/ss [Strafe Multiplier]", "Strafe Multiplier",
    "net/kohi/tcpnodelaymod/AUX", "TCPNoDelay Cheat",
    "Better Strafe Mod By Cheeky/Koupah", "Koupah Client #1",
    "koupah.Main", "Koupah Client #2",
    "Koupah/is/", "Koupah Client #3",
    "kohi/tcpnodelaymod/Tweaker", "TCPNoDelay Cheat",
    "IngameAccountSwitcher$1.class", "InGame Account Switcher",
    "stoud/merge", "Merge Client #1",
    "mergeclient", "Merge Client #2",
    "i[JQQI", "Merge Client #3",
    "YTQBFIXVF", "Merge Client #4",
    "Aimbot: False", "Merge Aimbot",
    "omikronclient.com", "Omikron Client #1",
    "Kyoctaviaprg.", "Omikron Client #2",
    "d[>L6", "Xanax Client or Canalex Keystrokes Client",
    "kiedHdNT>Z<RI", "Canelex Keystrokes Client #2",
    "_W_Y=6", "Wet Noodle/Magenta",
    "d[<N6", "Wet Noodle/Magenta",
    "tabbychat/injection", "TabbyChat Injection Client",
    "io/fishermen/fpsdisplay/settings/Wool.class", "CheatbreakerHUD Cheat",
    "necrum/Main.class", "Necrum Client",
    "kys/bleach/Bleach", "Bleach Client",
    "Cracked by Buddy [SirJava]", "SirJava Crack Signature",
    "pw/cinque/cpsmod/SpoofType.class", "CPSmod Spoofer",
    "&.EGO\\^`ijnoz|", "Wet Noodle",
    "pw/latematt/xiv/value/ClampedValue.class", "Latematt Client",
     "microsoft.visualBasic.powerpacks.dll",
    "removestring.exe",
    "remover.exe",
    "ts cleaner.bat",
    "dotnetaanmemory.dll",
    "420 v0.3.exe",
    "clicker.exe",
    "purityx",
    "3ms.exe",
    "inject_client.exe",
    "apollocracked.exe",
    "azranRemover.jar",
    "me.tojatta.clicker.ui.cl",
    "brplz is cute",
    "burger78.exe",
    "autoclicker",
    "dewgs.exe",
    "doggo.exe",
    "inject client.exe",
    "jnativehook",
    "l-clicker.jar",
    "work.txt.exe",
    "lsdclicker.xml",
    "autoclick.exe",
    "jacobschellman18",
    "boomy",
    "XAttr",
    "xreduszz",
    "s08yzx.exe",
    "pvper",
    "smart clicker v3.0.1.exe",
    "pause script",
    "suspend Hotkeys",
    "_snak3",
    "terio.jar",
    "cracked by dinkio",
    "anti bot",
    "auto armor",
    "auto clicker",
    "auto totem",
    "auto weapon",
    "bow aimbot",
    "criticals",
    "crystal aura",
    "killaura",
    "kill aura",
    "smoothaim",
    "autosoup",
    "anti fire",
    "anti hunger",
    "ghosthand",
    "anti aim",
    "anti desync",
    "anti sound lag",
    "anti vanish",
    "auto cheat",
    "auto disconnect",
    "auto reconnect",
    "discord rpc",
    "fancy chat",
    "log position",
    "middle click friend",
    "no srp",
    "self destruct",
    "air jump",
    "anti hazard",
    "auto jump",
    "auto walk",
    "baritone",
    "boatfly",
    "click tp",
    "elytra+",
    "fast fall",
    "high jump",
    "jesus",
    "levitation control",
    "long jump",
    "no push",
    "no slow",
    "safe walk",
    "anti afk",
    "auto eat",
    "auto eject",
    "auto farm",
    "auto fish",
    "auto mine",
    "auto tool",
    "chest stealer",
    "fast interact",
    "freecam",
    "item saver",
    "liquid interact",
    "no fall",
    "no rotate",
    "skin blinker",
    "anti blind",
    "anti overlay",
    "breadcrumbs",
    "camera clip",
    "chams",
    "clickgui",
    "crosshair+",
    "enchant color",
    "nametags",
    "no render",
    "storage esp",
    "tracers",
    "trajectories",
    "nacl_32",
    "yagami.exe",
    "l0li-0.2snapshot.exe",
    "loli client",
    "loli-hwid.exe",
    "math lesson 12 bac",
    "autoclicker",
    "cheatengine",
    "cheatengine",
    "cheatengine.exe",
    "cheatengine681.exe",
    "speedhack.dll",
    "speedhack-x86_64.dll",
    "lua53-64.dll",
    "monoscript.lua",
    "speedhack-i386.dll",
    "jd-gui",
    "autohot",
    "autohotkey",
    ".ahk",
    "liquidbounce",
    "impact client",
    "wurst",
    "huzuni",
    "wolfram",
    "sigma client",
    "aristois",
    "wwe client",
    "flare client",
    "skillclient",
    "blazing",
    "vape v",
    "flux",
    "phantom client",
    "iridium",
    "weepcraft",
    "autoclicker",
    "hcl client",
    "omikron",
    "sallos",
    "envy client",
    "matrix client",
    "nightmare",
    "luna client",
    "lina client",
    "suicide client",
    "obscure client",
    "tigur",
    "zecrus",
    "parallaxa",
    "pandora",
    "future client",
    "kami client",
    "inertia",
    "forgehax",
    "ares client",
    "rusherhack",
    "salhack",
    "baritone",
    "clicker",
    ".exe!2019/03/14:20:01:24",
    "OP AutoClicker",
    ".exe!2016/05/30:16:33:32",
    "GS AutoClicker",
    ".exe!2016/04/18:16:56:55",
    "AutoClicker",
    ".exe!2013/11/26:19:16:05",
    "MouseClicker",
    ".exe!2018/10/10:19:00:42",
    ".exe!2018/10/21:19:34:21",
    "Ecstasyy",
    ".exe!2018/07/24:11:25:57" ,
    "Apollo Lite",
    ".exe!2018/11/09:01:13:38" ,
    "GhostBytes",
    ".exe!2019/07/05:07:17:50" ,
    "Speed AutoClicker",
    "dev/zprestige/prestige/api/mixin/MixinLightmapTextureManager.classPK",
    "dev/zprestige/prestige/",
    "hit-delay",
    "hit delay",
    "FriendManager.class",
    "ProfileManager.class",
    "Nursultan-Br)bnl$",
    "Trigger-slls",
    "prestige",
    "D@9WH8LFWTNOWb4Z",
    "var14_8",
    "4IQwRJ4Sg0xj.exe",
    "NewLauncher.exe",
    "Nursultan.exe",
    "Ckp&aRc1nV,",
    "stop_cracking",
    "org/apache/core/g/c/",
    "org/apache/core/",
    "Nursultan NextGen",
    "addon3.jsonUT",
    "0WSNUcUZ7",
    "wingclient",
    "WingClient"
};